# Relative Reactivity Ratios for Two New 2-Chloro-1,3-Butadiene Systems

G. S. WICH and N. BRODOWAY, E. I. du Pont de Nemours and Company, Inc., Elastomer Chemicals Department, Wilmington, Delaware

###### Synopsis

The relative reactivity ratios in free-radical, emulsion copolymerizations for the systems 2-chloro-1,3-butadiene/methyl isopropenyl ketone and 2-chloro-1,3-butadiene/methacrylic acid were found to be 3.6 and 0.1 and 2.68 and 0.15, respectively. Consequently, copolymers are formed substantially richer in 2-chloro-1,3-butadiene units than the comonomer feed, have little alternation tendency, and do not form azeotropes. Distributions of monomer units in the copolymers are described.

## INTRODUCTION

The high relative reactivity of 2-chloro-1,3-butadiene in free-radical copolymerization with other dienes or activated olefins has been reported in both oil phase and emulsion systems.1,2 This paper describes the measurement of the relative reactivity ratios of 2-chloro-1,3-butadiene/methyl isopropenyl ketone and 2-chloro-1,3-butadiene/methacrylic acid monomer mixtures.

## EXPERIMENTAL MATERIALS AND METHODS

### Monomers

The 2-chloro-1,3-butadiene (chloropropene) was distilled from a 50% mixture with xylene (b.p. 59degC., \(\begin{equation*}{n}_{\mathrm{D}}^{\infty}\end{equation*}\) 1.4578) and stored under nitrogen below \(-20\)degC. without stabilization. The active oxygen content at reaction time was 10-20 ppm. The methyl isopropenyl ketone (MIPK) was freed from stabilizer and dimer by distillation. The fraction boiling at 29degC. (50 mm. Hg) was collected and stored below \(-20\)degC. Glacial methacrylic acid stabilized with 0.025% of _p_-methoxyphenol was employed without distillation. Analyses for carboxyl groups and unsaturation were made by titrating with standard solutions of base and bromine.

### Apparatus

Polymerizations were carried out in four-necked round-bottomed flasks fitted with agitators, thermometers, nitrogen inlets, burets, and hydrometer holders. The conversions were followed by measuring the changes in specific gravities with hydrometers calibrated in thousandths of a point.

### Polymerizations

All operations were carried out under nitrogen and the distilled water was purged with nitrogen before emulsification. Emulsion recipes employed are given in Table I. Since the methacrylate anion has been shown to be much less reactive in polymerization than the undissociated methacrylic acid,* the emulsion system for copolymerization of methacrylic acid was maintained at a pH of 2.5 or lower to keep the acid undissociated.

Polymerizations were initiated at 40 degC. by careful addition of a 5% solution of potassium persulfate. The internal temperature was maintained at 40 +- 0.5 degC. by external cooling. As soon as the specific gravity rose at least 0.003 point, the copolymerizations were arrested by pouring the entire emulsion into methanol containing a trace of a polymerization inhibitor such as phenothiazine.

### Purification of Analytical Samples

Copolymers of 2-chloro-1,3-butadiene and methyl isopropenyl ketone were purified by repeated extractions with acetone. Similar treatment of a polychloroprene control yielded a reference value of 39.4% chlorine. Co-polymers of 2-chloro-1,3-butadiene and methaerylie acid were purified by double precipitation from tetrahydrofuran solutions, water being used as the nonsolvent. The copolymers were dried at room temperature _in vacuo_.

## DISCUSSION OF RESULTS

### Determination of Relative Reactivity Ratios

The usual assumptions have been employed concerning the kinetic chain length, the existence of a steady state, and the constancy of monomer feed

\begin{table}
\begin{tabular}{c c c}  & Parts per hundred of monomer \\ Material & A & B \\
2-Chloro-1,3-butadiene & 100 \(\rightarrow\)_α_ & 100 \(\rightarrow\)_α_ \\ Methyl isopropenyl ketone & _α_ & — \\ Methacrylic acid & — & _α_ \\ _tert_-Dodecyl mercaptan & 1.5 & — \\ Oleie acid & 4.0 & — \\ Distilled water & 150 & 150 \\ Lomar PW• & 4.0 & — \\ Sodium hydroxide & 1.076 & — \\ Ultrawet Kb & — & 2.0 \\ \end{tabular}
\end{table} TABLE I: Emulsion Recipescomposition at low conversion.4 Furthermore, the presence of mercaptan modifier was assumed not to affect the relative reactivities.

Fineman and Ross8 have derived the following expression which permits straightforward calculation of relative reactivity ratios \(r\)1 and \(r\)2 from co-polymerization data:

\[\frac{f_{1}(1\,-\,2F_{1})}{(1\,-\,f_{1})F_{1}}=r_{2}+\left[\frac{f_{1}{}^{2}(F_{1}\,-\,1)}{(1\,-\,f_{1})^{2}F_{1}}\right]r_{1} \tag{1}\]

where \(f\)1 denotes the mole fraction of unreacted monomer M1 in the feed and \(F\)1 denotes the mole fraction of M1 monomer units in the increment of co-polymer formed at the initial stage of copolymerization.

Each value of \(f\)1 was taken to be the mole fraction of 2-chloro-1,3-butadiene in the initial monomer feed mixture. Each value of \(F\)1was obtained by analysis of the copolymer for chlorine. The copolymer composition data for emulsion-copolymerized 2-chloro-1,3-butadiene and methyl isopropyl ketone are given in Table 2. These data employed in eq. (1) yielded the straight line plot in Figure 1. The slope of the line is 3.6 and represents \(r\)1 (M1 = 2-chloro-1,3-butadiene). The intercept at the \(y\) axis gives \(r\)2 (M2 = methyl isopropenyl ketone) = 0.1.

The corresponding copolymer composition data for the emulsion copolymerization of 2-chloro-1,3-butadiene and methacrylic acid are contained in

\begin{table}
\begin{tabular}{c c c c}  & Chlorine in & \multicolumn{2}{c}{Male fraction of 2-chloro-1,3-butadiene} \\ Conversion, \% & copolymer, \% & Feed (_f_1) & Copolymer (_F_1) \\ — & 39.4 & 1.00 & 1.00 \\
5.3 & 36.2 & 0.74 & 0.92 \\
7.9 & 35.7 & 0.69 & 0.90 \\
4.7 & 34.3 & 0.59 & 0.86 \\
9.2 & 31.9 & 0.49 & 0.80 \\
8.5 & 29.9 & 0.39 & 0.75 \\
13.3 & 20.5 & 0.19 & 0.51 \\ \end{tabular}
\end{table}
Table 2: Dependence of Copolymer Composition on Monomer Feed for the 2-Chloro-1,3-Butadiene and Methyl Isopropenyl Ketone System

\begin{table}
\begin{tabular}{c c c c}  & Chlorine in & \multicolumn{2}{c}{Male fraction of 2-chloro-1,3-butadiene} \\ Conversion, \% & copolymer, \% & Feed (_f_1) & Copolymer (_F_1) \\
5.07 & 38.4 & 0.898 & 0.958 \\
3.48 & 36.8 & 0.795 & 0.918 \\
1.21 & 34.7 & 0.694 & 0.865 \\
3.25 & 33.2 & 0.587 & 0.826 \\
3.72 & 27.4 & 0.393 & 0.681 \\ \end{tabular}
\end{table}
Table 3: Dependence of Copolymer Composition on Monomer Feed for the 2-Chloro-1,3-Butadiene and Methyl Isopropyl Ketone SystemFigure 2: Relative reactivity plot for 2-chloro-1,3-butadiene/methacrylic acid copolymerization. Slope \(\approx\)\(r_{1}\) = 2.7 \(\pm\) 0.2, \(y\) axis intercept \(=\)\(r_{1}\) = 0.15 \(\pm\) 0.05.

## Relative reactivity ratios

Table III.When employed in eq. 1, the above data yielded the straight line plot shown in Figure 2. From the slope \(r_{1}\) is 2.7 (2-chloro-1,3-butadiene) and from the intercept at the \(y\) axis \(r_{\text{s}}\) is 0.15 (methacrylic acid).

### Detailed Structure of Copolymer Chains

In both cases the copolymers were formed relatively richer in 2-chloro-1,3-butadiene than the commoner feed. This is a consequence of the preference of both 2-chloro-1,3-butadiene radical (m1') and methyl isopropyl ketone or methacrylic acid radical (m2') for 2-chloro-1,3-butadiene (M1) monomer. The arrangements of the monomer units in the copolymers are also similar. Copolymerization zero-ropes are unlikely since both \(r_{1}\) and \(r_{1}\) are not greater than unity or less than unity. The alternation tendency is small since \(r_{1}\) and \(r_{2}\) are not simultaneously close to zero.

The distributions of the sequence lengths of 2-chloro-1,3-butadiene and methyl isopropyl ketone or methacrylic acid units were calculated by known methods[8] for copolymers prepared from equimolar monomer mixtures. These are shown in Tables IV and V.

Less than 1% of the methyl isopropyl ketone sequences contain more than two monomer units, whereas over 60% of the 2-chloro-1,3-butadiene sequences contain more than two monomer units. Similarly, only 1.7% of the methacrylic acid sequences contain more than two monomer units,

\begin{table}
\begin{tabular}{c c c} Units per sequence & \% of 2-Chloro-1,3-butadiene/Methyl Isopropenyl Ketone \\ Units per sequence & \% of 2-Chloro-1,3-butadiene sequences & \% of \\  & butadiene sequences & MIPK sequences \\
1 & 21.8 & 90.9 \\
2 & 17.1 & 8.26 \\
3 & 13.3 & 0.75 \\
4 & 10.4 & 0.068 \\
5 & 8.2 & 0.0962 \\ \textgreater{}5 & 29.2 & 0.0158 \\ \end{tabular}
\end{table}
Table IV: Distribution of Sequence Lengths in Copolymer From Equimolar Monomer Mixture (2-Chloro-1,3-Butadiene/Methyl Isopropenyl Ketone)

\begin{table}
\begin{tabular}{c c c} Units per sequence & \% of 2-Chloro-1,3-butadienewhereas 53% of the 2-chloro-1,3-butadiene sequences contain more than two monomer units. Thus both copolymers are elastomers resembling in properties the homopolymer of 2-chloro-1,3-butadiene.

Infrared spectra confirm that 2-chloro-1,3-butadiene units in the copolymers are present in all possible modes of addition, and that these structures are present in the same ratio as in the homopolymer prepared at the same temperature.

### Comparison with Other 2-Chloro-1,3-butadiene Copolymerizations

The relative reactivities obtained show the same high reactivity for 2-chloro-1,3-butadiene as do previously reported copolymerizations shown in Table 6. Alternation is reported only with the highly polar vinylidene cyanide.11

The \(Q\) and \(e\) values for 2-chloro-1,3-butadiene, based on its copolymerization with butadiene,1 are calculated to be 8.07 and 0.46, respectively. The reported \(Q\) and \(e\) values for methacrylic acid12 are 2.0 and 0.7, respectively. Based on the copolymerization of vinylidene chloride and methyl isopropenyl ketone,12 the \(Q\) and \(e\) values for methyl isopropenyl ketone are 1.95 and 1.23, respectively. Thus, the calculated relative reactivities for 2-chloro-1,3-butadiene/methacrylic acid are 4.5 and 0.21, and for 2-chloro-1,3-butadiene/methyl isopropenyl ketone are 5.9 and 0.094, in fair agreement with the experimental values.

The high \(Q\) value of 2-chloro-1,3-butadiene indicates the strong tendency of the monomer to add to radicals. The relatively neutral \(e\) value permits the radical to react with only small alternating tendencies with both electron-releasing and electron-attracting substituents in the comonomer.

## References

* [1] Simha, R., and L. A. Wall, _J. Res. Natl. Bur. Std._, **41**, 521 (1948).
* [2] Mayo, F. R., and C. Walling, _Chem. Res._, **46**, 191 (1950).
* [3] Katchalsky, A., and G. Blauer, _Trans. Faraday Soc._, **47**, 1360 (1951).
* [4] Flory, P. J., _Principles of Polymer Chemistry_, Cornell Univ. Press, Ithaca, N. Y., 1953, pp. 178-199.
* [5] Fineman, M., and S. D. Ross, _J. Polymer Sci._, **5**, 259 (1950).
* [6] Alfrey, T., Jr., J. J. Bohrer, and H. Mark, _Copolymerization_, Interscience, New York, 1952, pp. 133-145.
* [7] Alfrey, T., Jr., A. I. Goldberg, and W. P. Hohenstein, _J. Am. Chem. Soc._, **68**, 2464 (1946).
* [8] Dosk, K. W., and D. L. Dineen, _J. Am. Chem. Soc._, **73**, 1084 (1951).
* [9] Mitsengendler, S. P., V. N. Krasulina, and L. B. Trukhmanova, _Inv. Akad. Nauk SSSR, Otdel. Khim. Nauk_, **1956**, 1120.
* [10] Koton, M. M., and O. K. Surnina, _Dokl. Abad. Nauk SSSR_, **113**, 1063 (1957); also M. M. Koton, _J. Polymer Sci._, **30**, 331 (1958).
* [11] Gilbert, H., F. F. Miller, S. J. Averill, E. J. Carlson, V. L. Folt, H. J. Heller, F. D. Stewart, R. F. Schmidt, and H. L. Trumbull, _J. Am. Chem. Soc._, **78**, 1669 (1956).
* [12] Chapin, E. C., G. E. Ham, and C. L. Mills, _J. Polymer Sci._, **4**, 597 (1949).
* [13] Ushako, S. N., and L. B. Trukhmanova, _Inv. Akad. Nauk SSSR, Otdel. Khim. Nauk_, **1957**, 980.

## Resume

On a etudie les rapports de faculivite relative des systemes 2-chloro-1,3-butadiene-methylisopropenyletone et 2-chloro-1,3-butadiene acide methacrylique au cours de leur copolymerisation en emulsion en presence de radicaux libres. Ces valeurs s'elevent respectivement 4 s.6 et 0.1, et 2.7 et 0.15. Par consequent, les copolymers formes sont consid'rablement enrichis en unites de 2-chloro-1,3-butadiene compares au melange des commonomeres de depart. II y a peu de tendance d'al'alternance et aucun azeotrope n'est forme. On a donne des details sur la distribution des unites de monomrees au sein des copolymers.

## Zusammenfassung

Die relativen Reaktivitatsverhaltnisse fur die radiklasische Emulsionsopolymerisation der Paare 2-Chlor-1,3-butadiene-Methylisopropenylketon und 2-Chlor-1,3-butadiene-Methylsaure wurden zu 3,6 und 0,1 bzw. 2,7 und 0,15 bestimmt. Demzufolge enthalten die Copolymeren wesentlich mehr 2-Chlor-1,3-butadien-Einheiten als die vorgegebene Monomermischung, zeigen geringe Alternationstendenz und bilden kein Azeotrop. Die Verteilung der Monomereinheiten in den Copolymeren wird beschrieben.

## Received July 30, 1962

Revised November 30, 1962