\(\gamma\)-RAY INITIATED COPOLYMERIZATION OF ETHYLENE AND CARBON MONOXIDE*

The purpose of this note is to report the monomer reactivity for the copolymerization of ethylene and carbon monoxide initiated by Co600 g-rays. The data of Brubaker et al. (1), and Coffman et al. (2), who synthesized this copolymer by conventional peroxide initiators were correlated and a comparison for (a) the ratio of specific rate constants was made.

### Experimental

A number of runs were made in which the initial mole concentration of the two monomers was varied as shown in Table I.

TABLE I

\(\bullet\)Work performed under the auspices of the U. S. Atomic Energy Commission, Division of Isotope Development.

## 3 Conclusion and Results

The experimental data obtained in the study of the gamma initiated copolymerization of ethylene and carbon monoxide is given in Table 1. Polymerizations were carried out to low conversions in order to minimize the possibility of depleting either of the monomers. The data in Table 1 were found to obey a simplified form of the copolymer composition equation (3-5):

\[\frac{b}{a} = \frac{B}{A} \cdot a \cdot \frac{\beta B + A}{aB + A}\]

The above equation states that a mixture of the two monomers in the molar ratio B/A should yield an initial copolymer with the molar ratio b/a.

The assumption is made that if monomers A and B undergo reaction, free radicals of the type A* and B* are formed and react in four possible modes of monomer addition. The four reactions are governed by the propagation rate constants K**aa, K**ab, K**ba, and K**bb. The composition of the copolymer can be determined from the ratio of the rate constants:

\[a = \text{K}_{\text{ab}}/\text{K}_{\text{aa}},\qquad\text{ and }\qquad\beta = \text{K}_{\text{bb}}/\text{K}_{\text{ba}}\]

If carbon monoxide is designated as component B of the monomer mixture, the rate constant K**bb vanishes and \(b\) = 0 since carbon monoxide

Fig. 1: A comparison of \(a\) values for ethylene-carbon monoxide copolymer systems.

does not polymerize alone. In this case, eq. (1) reduces to the simplified form:

\[\text{a/b = 1 + (A/aB)}\]

A plot of a/b vs. A/B, using the experimental data in Table I, yields a straight line of slope 1/a with an intercept of 1, as predicted by eq. (2).

The data in Table I, as plotted in Figure 1, yields a straight line of the slope 1/22.0 (a = 22), indicating that carbon monoxide monomer adds 22 times as fast as an ethylene monomer to an ethylene free radical chain end.

In a similar manner, values for a were also calculated from experimental data presented by Brubaker et al. (1), and Coffman et al. (2), who studied the ethylene-carbon monoxide copolymer system using conventional peroxide initiators. The a value, calculated from Brubaker's data for experiments carried out in cyclohexane at 136 atm. and 135degC., was 2.0, while that for Coffman's data performed without solvent at pressures ranging from 850-1,000 atm. and temperatures between 120-130degC., was 6.8. The differences in experimental conditions may account for the wide variation of a values; however, it seems significant that in the radiation process the carbon monoxide is induced to add to an ethylene free radical chain end to a much greater degree than in the conventional free radical initiation process.

Figure 2: Comparative I.R. spectra for polyethylene and polyethylene-carbon monoxide copolymer.

Figure 2 shows an infrared spectrum for the ethylene-carbon monoxide copolymer and for pure polyethylene produced by gamma radiation as described by Steinberg et al. (6).

The only characteristic polyethylene band remaining unaffected in the ethylene-carbon monoxide copolymer spectrum is the C-H stretch band at 3.4 \(\mu\). The change in the C-H bending vibration at 6.8 \(\mu\) has been assigned to a methylene structure adjacent to a carbonyl. The doublet at 13.7 and 13.9 \(\mu\) indicating four or more carbons in a chain became a singlet and decreased in intensity. The strong carbonyl absorption at 5.8 \(\mu\) and its harmonic at 2.9 \(\mu\) indicate a polyketone structure.

More detailed data on the experimental techniques and the physical and chemical properties of these copolymers will be published later.

## References

- (1) Brubaker, M. M., D. D. Coffman, and H. H. Hoehn, J. Am. Chem. Soc., 74, 1509 (1952).
- (2) Coffman, D. D., P. S. Kinkney, F. T. Wall, W. H. Wood, and H. S. Young, J. Am. Chem. Soc., 75, 3391 (1952).
- (3) Alfrey, T., Jr., and G. Goldfinger, J. Chem. Phys., 12, 205 (1944).
- (4) Mayo, F. R., and F. M. Lewis, J. Am. Chem. Soc., 66, 1594 (1944).
- (5) Wall, F. T., J. Am. Chem. Soc., 66, 2050 (1944).
- (6) Steinberg, M., P. Colombo, L. Kukacka, R. N. Chapman, and G. Adler, "Proceedings of the International Symposium on Radiation-Induced Polymerization and Graft Copolymerization," Battelle Memorial Institute, pp. 70-106, (Nov. 29-30, 1962), and BNL 740 (T-238) (1962).
- (7) P. Colombo M. Steinberg J. Fontana

### Brookhaven National Laboratory

Upton, New York

Received June 13, 1963