# See https://setuptools.readthedocs.io/en/latest/build_meta.html
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "copolymer-reactivity"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "requests",
    "crossrefapi",
    "pdf2image",
    "openai",
    "backoff",
    "pubchempy",
    "diskcache",
    "pyyaml",
    "pandas",
    "scikit-learn",
    "xgboost",
    "beautifulsoup4",
    "selenium",
    "pytesseract",
    "opencv-python",
    "Pillow",
    "thefuzz",
    "pint",
    "anthropic",
    "numpy",
    "imutils",
    "rdkit",
    "doi2pdf",
]

[project.optional-dependencies]
testing = [
    "pytest>=7.0",
    "pytest-cov",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 100
target-version = ["py38", "py39", "py310", "py311"]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
include_trailing_comma = true
reverse_relative = true
