wandb_version: 1

model:
  desc: null
  value: gpt-4-vision-preview
paper number:
  desc: null
  value: 10
token length:
  desc: null
  value: ''
input:
  desc: null
  value: images
number of model calls max:
  desc: null
  value: 3
number of model calls min:
  desc: null
  value: 2
temperature:
  desc: null
  value: ''
deviation of correct rxn:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.2
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712125895.856176
    t:
      1:
      - 5
      - 53
      - 54
      - 55
      - 95
      - 97
      - 105
      2:
      - 5
      - 53
      - 54
      - 55
      - 95
      - 97
      - 105
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.16.2
      8:
      - 4
      - 5
      13: darwin-arm64
