###### Abstract

**solvents if a metal with low ionization potential or hydrocarbons with considerable electron affinity be selected. The resultant complexes initiate polymerization of styrene in various media. Certain generalizations in the formation of metal-aromatic complexes in various media are discussed. In particular it has been noted that the deviation of alkali metal activity from the order Li \(<\) Na \(<\) K (Li is often more active than Na) may be explained by the increasing tendency of the cation towards solvation with decrease in its radius.**

**Studies in Cyclic Polymerization and COPOLYMERIZATION -IV. SYNTHESIS OF SOME DIVINYL- AND DILSOPROPENYLACETAL AND STUDY OF THEIR CYCLIC POLYMERIZATION**

S. G. Matsoyan, M. G. Avetyan, L. M. Akopyan, M. G. Voskanyan, N. M. Koryan and M. A. Eliazyan, Vyskomol. soedin. **3**: No. 7, 1010-1014, 1961.

Divinylproional, divinylisobutyral, divinylisoamylal, diisopropylformal and diisopropylbutyral have been synthesized via dehydrochlorination of the corresponding \(b\),_b_'-diichloroacetals. The capacity of these monomers to undergo cyclic polymerization has been investigated. Polymerization of divinylpropional, divinylisobutyral and divinylisoamylal in the presence of radical initiators has been shown to take place, similarly to the previously described divinylacetals, by the cyclic mechanism with the formation of acetal derivatives of polyvinyl alcohols, i.e. polyvinylacetals. In contrast to nonsubstituted divinylacetals, diisopropenylformal and diisopropylbutyral do not polymerize in the presence of initiators of radical polymerization.

**Gamma-Ray Induced COPOLYMERIZATION OF ACRYLONITRILE AND ETHYLENE V. F. Gromov, P. M. Khomikovskii and A. D. Abkin, Vyskomol. soedin. **3**: No. 7, 1015-1019, 1961.

The _g_-ray induced copolymerization of ethylene and acrylonitrile in toluene at 20\({}^{\circ}\) has been investigated. It has been found that the rate of the process and the mean molecular weights of the polymers increase with the increasing acrylonitrile content. The copolymers are enriched in acrylonitrile for all monomer ratios. The monomer reactivity ratios calculated from the copolymer compositions are _r_I(AN) = 7 and \(r\)2 = 0.

**Studies in the Polymerization of Vinyl Early ethers and of their Derivatives - I. POLYMERIZATION AND COPOLYMERIZATION OF VINYL ethers of Halogenated Phenols**

A. V. Kalabina, A. Kh. Fillipova, G. V. Smitrieva and L. Ya. Tsarik, Vyskomol. soedin. **3**: No. 7, 1020-1026, 1961.

A comparative study has been made of the polymerization of vinyl ethers of 4-chloro-, 4-bromo, 2,4-dichloro and pentachlorophenols in the presence of the etherates of boron trifluoride. The effect of time and temperature of the reaction and of the amount of catalyst on the polymer yield has been ascertained. It has been found that in the series of the _p_-monosubstituted ethers the highest tendency towards cationic polymerization is manifested by the vinyl ether of 4-bromophenol and the least by the ether of 4-fluorophenol. Among the chlorophenol ethers the tendency towards cationic polymerization falls with increase in the number of chlorine atoms. The polymers obtained in all the experiments were colourless solids of molecular weight _ca._ 1500 and melting temperature 60-80\({}^{\circ}\). It has also been shown that the vinyl ethers of chlorophenols may copolymerize with methyl-methacrylate and styrene.