KARGIN, Vysokomol. soyed. A9: 1316, 1967 (Translated in Polymer Sci. U.S.S.R. 9: 6, 1473, 1967)
12. E. HELLMUTH and B. WUNDERLICH, J. Appl. Phys. 36: 3039, 1965
13. V. G. NIKOL'SKII and N. Ya. BUBEN, Dokl. Akad. Nauk SSSR 134: 134, 1960; Vysokomol. soyed. 4: 922, 1962 (Not translated in Polymer Sci. U.S.S.R )
14. N. Ya. BUBEN, V. I. GOL'DANSKII, L. Yu. ZLATKEVICH, V. G. NIKOL'SKII and V. G. RAYEVSKII, Vysokomol soyed. A9: 2275, 1967 (Translated in Polymer Sci. U.S.S.R. 9: 10, 2575, 1967)
15. V. G. NIKOL'SKII, Ideen des exakten Wissens, 555, 1971
16. V. G. NIKOL'SKII, Dassertation, 1966
17. V. G. NIKOL'SKII and G. M. BURKOV, Khm. vys. energu 5. 416, 1971
18. C. W. BUNN, Trans. Faraday Soc. 35: 482, 1939
19. J. D. GORMAN, G. WILLIAMS and E. PASSAGLIA, Perekhody i relaksatsionnye yavleniya v polmerakh (The Transitions and Relaxation Phenomena in Polymers). p. 193, Izd. "Mir", 1968
20. K. H. ILLERS, Rheol Acta 3: 202, 1964
21. A. PETERLIN, Croatica chemica Acta 42: 335, 1970
22. E. PASSAGLIA, M. GORDON and G. M. MARTIN, J Res. Nat. Bur. Standards A68: 519, 1964
23. A. CRISMANN and E. PASSAGLIA, J. Res. Nat Bur Standards A70. 225, 1966
24. I. MASAKAZU, J. Polymer Sci. 55: 443, 1961
25. Mo A. I. HUGH and I. M. SCHULZ, Phil. Mag. 24: 155, 1971
26. R. F. BOYER, Rubber Chem. and Technol. 36: 1303, 1963
27. J. WADA, R. NAYAKAWA and T. NISHI, J. Polymer Sci C15: 101, 1961
28. I. M. SINNOTT, J. Polymer Sci. B3 945, 1965, Polymer Preprints 6: 652, 1965

STUDY OF THE KINETICS OF POLYMERIZATION AND COPOLY-MERIZATION OF METHACYLIIC ACD SULPHOLANATE*

A. I. Vorob'eva, E I. Ablyakimov, G. V. Leplyanin, S. R. Rafikov and G. P. Gladyshev

Chemistry Institute, Bashkir Branch U.S S.R. Academy of Sciences

(Received 7 July 1972)

The kinetics of polymerization of methacrylic acid sulpholanate (MAS) of its copolymerization with methyl methacrylate, styrene and methacryhe acid were investigated. An increased actuvity of MAS was noticed, when compared with the majority of known methacrylates, in the radical polymerization reactions.

Sulphur contaming polymers have a number of valuable properties, especially heat, temperature, light and chemical stability [1-4], large dielectric and physico-chemical characteristics [1, 5], good adhesion to various materials [6]. Thistype of polymer has been given much attention in recent years [7, 8, 10]. The polymerization of sulphur containing vinyl monomers and their copolymerization with various other monomers represents a very promising method of synthesizing sulphur containing polymers, and of modifying already widely used ones. The sulpholanates of unsaturated acids belong to the interesting monomers [9]. No information could be found in the literature to their polymerization kinetics. We therefore describe in this report the results of studying the radical homo- and copolymerization kinetics of MAS, and some of the properties of our products.

## Experimental

The MAS (CH2=C-COO-) has a b p = 158degC/1 mmHg; \(n_{D}^{20}\) 1 5028, \(d_{4}^{20}\) 215, m.p = 39-40degC. Elemental analysis gave: (%): 47 0 C, 6 0 H, 15 8 S. The absorption bands found in the infrared (IR) spectra (cm-1) are: 1132, 1143, 1287, 1328 (SO2-groups); 1378, 1448, 2960 (CH2-groups); 1400, 2920 (CH2-groups); 947, 1017, 1630, 3020, 3040 (C=C bonds); 1132 (--COC-groups); 1715 (O=C-groups).

Styrene and methyl methacrylate (MM) were purified by the usual methods [11], the b.p. of styrene was 42degC/15 mmHg, \(n_{D}^{20}\)=1 5465. The MM had b p = 46degC/100 mmHg, \(n_{D}^{10}\) 1 4130. The methacrylic acid (MA) was dried over anhydrous calcium chloride and was three vacuum distilled; b p. = 44 5degC/2 mmHg, \(n_{D}^{10}\) 1 4315. The azoisobutyrodunitrile (AIBN) was recrystallized three times from methanol and then vacuum dried to constant weight; m.p. = 102degC. All the solvents used in the polymerizations were purified by the usual methods [12] and had the tabulated characteristics.

The knetestes of homo- and copolymerization were studied by dilatometry at low conversion (less than 10%) m the presence of AIBN (0-01% w/w) The dilatometers were fused after evacuation to 10-10-4mmHg. In all cases, with the exception of the determination of the order of reaction with respect to monomer, the monomer to solvent ratio used was 1 : 1. Contraction coefficient \(K\) of MAS was established after several tests from the polymer yield at 50degC; it was 0 142. An estimate of \(K\) for the copolymerization was based on the additivity principle using the known values of \(K\) of other monomers [13, 14].

The polymers were purified by 3-4 repreeptatons followed by vacuum drying at 60degC. The homopolymer was repreperitated with sulphate ether from DMF. The solvents and preepitants used to punfy the copolymers are given in Table 1. The copolymer compositions were determined by elemental analysis. The copolymerizaton constants were determined by the method described by Mayo and Lewis [15].

## Results

The kinetics of polymerization of MAS were studied in DMF, DMSO and benzene as solvents. There were difficulties in the latter due to the heterogeneity of the medium at higher MAS concentrations.

Table 2 and Figs. 1, 2 show that the nature of the solvent does not affect the rate of MAS polymerization. The orders of reactions with respect to monomer and initiator found graphically were 1 and 0-5 respectively (Fig. 1, 2), which indicates the presence of the usual mechanism of radical polymerization with a bimolecular cham termination. It was interesting to note that the rate of MAS polymerization exceeded that of numerous known methacrylates; this is probably

[MISSING_PAGE_EMPTY:3]

due to the effect of the polar SO_a_-group in the sulpholan ring producing steric hindrance to chain termination. The true activation energy \(E\) of the polymerization found by the graphic method was 23 kcal/mole (Table 2).

The studies of the kinetics of copolymerization with vinyl monomers, i. e. MM, styrene and MA, were carried out under homogeneous conditions The results are reproduced in Table 3 and Fig 3. The copolymerization constants \(r\)1 are evidence of the high activity of MAS in the copolymerizations. The explanation is, judging from the large _Q_-values calculated for MAS by the Alfrey-Price method [18] on the MAS copolymerization with MM and styrene, the increase of the conjugation energy of the monomer. The _Q_-value for MAS was not calculated, according to the results of its copolymerization with MA due to dependence of \(Q\) on the type of comonomer and medium in this case [19, 20].

The rate of the bulk copolymerization of MAS with styrene increased on raising the content of the first monomer in the original mixture (Fig. 3_b_). This

\begin{table}
\begin{tabular}{c|c|c|c} \hline \multirow{2}{*}{**Solvent**} & \multirow{2}{*}{**Process temp., °C**} & \(\&\times 10^{4}\),* & \multirow{2}{*}{\(k_{\text{p}}/k_{\text{o}}^{\text{i}}/\text{t}\)} \\  & & & 1. mole−1 - sec−1 & \\ \hline \multirow{2}{*}{**DMF**} & 40 & 2.8 & 0-35 \\  & 50 & 2.8 & 0-48 \\  & 60 & 25 & 0-75 \\  & 70 & 56 & 0-10 \\ DMSO & 50 & 8-1 & 0-45 \\ Benzene & 50 & — & 0-43 \\ \hline \end{tabular}
\end{table}
Table 2: THE MAS copolymerization kinetics with AIBN as initiator ([AIBN]=6·1 × 10−4 mole/l.)

\begin{table}
\begin{tabular}{c|c|c|c|c|c|c|c|c|c} \hline \multirow{2}{*}{**M\({}_{\text{a}}\)**} & \multicolumn{2}{c|}{**M\({}_{\text{a}}\), mole\%**} & \multirow{2}{*}{\(r_{\text{1}}\)} & \multirow{2}{*}{\(r_{\text{8}}\)} & \multirow{2}{*}{\(r_{\text{1}}\)} & \multirow{2}{*}{\(r_{\text{1}}\)} & \multirow{2}{*}{\(r_{\text{1}}\)} & \multirow{2}{*}{\(Q\)} & \multirow{2}{*}{\(e\)} & \multirow{2}{*}{\(\varphi\)} \\ \cline{3-3} \cline{5-10}  & \multicolumn{2}{c|}{**at start**} & & & & & & & & \\  & \multicolumn{2}{c|}{} & \multicolumn{2}{c|}{mer} & & & & & & \\ \hline \multirow{2}{*}{**Styrene**} & 97·14 & 88·87 & 1 5·0·1 & 0·22 ± 0 01 & 0·33 & 2·0 & 0·26 & 25 \\  & 94·06 & 8·0·16 & & & & & & & \\  & 75·8 & 63·8 & & & & & & \\ \cline{1-1}
**MM** & 96·21 & 9·6·14 & 3 34·0 25 & 0·67·0 & 0·2 24 & 2·5 & 0·4 & 5 \\  & 92·06 & 8·7·20 & & & & & & \\  & 80·9 & 6·8·60 & & & & & & \\ \cline{1-1}
**MA** & 96·6 & 9·59 & 1 0·8·0·1 & 0·8·3± 0 02 & 0·83 & — & — & 600 \\  & 8·9·5 & 8·7·9 & & & & & & \\  & 84·7 & 8·2·7 & & & & & & \\ \hline \end{tabular}
\end{table}
Table 3: THE MAS (M\({}_{\text{a}}\)) copolymerization with some vinyl monomers (M\({}_{\text{a}}\)) ([AIBN]=6·1 × 10−4 mole/l.)is probably the consequence of MAS radicals being more reactive than those of styrene. In the case of MM as comonomer in benzene as solvent (Fig. 3_a_), or MA in DMF (Fig. 3_c_) (using small MAS additions), the reverse was true, i.e. the rate of copolymerization dropped as the MAS content increased in the substrate. This indicates the MAS radicals to be less reactive than those of MM or MA.

The cross termination constants _ph_ became smaller on changing from MAS-styrene to MAS--MM, while value of \(r\)1*_r_2 became larger (Table 3). This is explained by the monomers having different polarities in the first case, but similar ones in the second. There was in system MAS-MM the same tendency for cross termination (_ph_=5). Undesirably large values of _ph_ were encountered during the copolymerization of MAS with MA and the explanation must be sought in the solvent, i.e. DMF, which easily formed complexes with MA.

Poly-MAS is a white powder soluble in DMF and DMSO, but insoluble in benzene, acetone, chloroform, dioxane,4butyl acetate, alcohols, paraffins. Typical IR-spectral absorption lines are (cm-1): 1120, 1135, 1307 (SO4-groups); 1185 (RCOOR'-groups); 1720 (CO-groups). The molecular weight (mol.wt.) of the

Figure 1: The effect of the MAS concentration on the rate of polymerization _ν_ in: _1_—DMF, _2_—DMSO, _3_—benzene at 50°C using 6*53 × 10−4 mole/l. AIBN.

Figure 2: The effect of the intratator concentration _σ_ on the rate of the MAS polymerization in DMF at 50°C using 2*04 mole/l. MAS.

polymer produced in DMF at 60\({}^{\circ}\)C, determined by light-scattering, was 880,000 ([\(\eta\)]=0*79 in DMF at 20\({}^{\circ}\)C).

Thermomechanical testing showed two transition temperatures, i.e. the softening temp.=197\({}^{\circ}\)C, flow temp.=250\({}^{\circ}\)C, start of decomposition at about 240\({}^{\circ}\)C.

The copolymers were white powders. Table 1 shows the solubilities of the copolymers, typical IR-spectral absorption lines and the thermomechanical properties. The mol.wt of the MM copolymer containing 12*8% MAS produced in benzene at 50\({}^{\circ}\)C was 800,000. The insertion of the MAS units into the copolymer with styrene or MM raised the softening temperature and that of flow. The MA copolymers with MAS had lower softening and flow temperatures than the polymethacrylic acid alone.

## References

* [1] G. MORNEAU, Mod. Plast. 47: 150, 1970
* [2] G. F. D'ALELIO, U. S. Pat. 3518233, 1970
* [3] V. V. KORSHAK, A. A. IZYNEYEV, N. Sh. ALDAROVA and V. Ya. YERVSHEV, Russian Authors' Cert. No. 233905, 1970; Byull. izobret., No. 3, p. 78, 1967
* [4] S. M. GOHEN and R. H. YOUNG, U.S. Pat. 3518235, 1970
* [5] A. HIPPEL and L. G. WEISSON, Ind. Eng. Chem. 38: 1121, 1946
* [6] H. A. SMITH, U.S. Pat. 3371073, 1968
* [7] V. V. KORSHAK (Ed.), Uspekhi v oblasti sinteza elemento-organi cheeskikh polimerov (Advances in the Synthesis of Organo-metallio Polymers). Izd. "Nauka", 1966
* [8] E. J. GOETHALS, J. Macromol. Sci. 2: 74, 1968
* [9] U. S. Pat. 3253719; Chem. Ab. 65: 20245c, 1966
* [10] P. CHOSH, J. Polymer Sci. D: Macromol. Revs. 5: 195, 1971
* [11] V. V. KORSHAK (Ed.), Sb.: Monomery (In: Monomers). Izd. inostr. lit., 1951
* [12] A. WEISSBERGER, E. PROSKAUER, J. RIDDICK and E. TUPPS, Organi cheeskie rastvoriteli (Organic Solvents). Izd. inostr. lit., 1958
* [13] G. P. GLADYSHEV and K. GIBOV, Polimerizatsiya pri glubokikh stepenyakh prevrasheheniya i metody eye isaledovanya (High-efficiency Polymerization and Methods of its Study). Izd. "Nauka", 1968
* [14]**A. V. ANGELOVA, Yu. L. SPIRIN** and **R. Ye. KOVAL'CHUK,** Vysokomol. soyed **A12:** 2703, 1970
* [15]**F. R. MAYO** and **F. M. LEWIS**, J. Am. Chem. Soc **66:** 1594, 1944
* [16]**C. G. OVERBERGER, M. T. 0'SHAUGHNESSY** and **H. SHALT,** J. Am. Chem. Soc. **71:** 2661, 1949
* [17]**Kh. S. BAGDASARYAN,** Teoruya radikal'noi polimerzatsii (The Theory of Radical Polymerization). Izd. Akad. Nauk SSSR, 1959
* [18]**T. ALFREY** and **C. PRICE**, J. Polymer Sci. **2:** 101, 1947
* [19]**A. V. RYABOV, Yu. D. SEMCHIKOV** and **N. N. SLAVNTISKAYA,** Vysokomol soyed. **A12:** 553, 1970 (Translated in Polymer Se. U.S.S.R. **12:** 3, 623, 1970)
* [20]**Yu. L. SPIRIN,** Uspekhn khm **33:** 1201, 1969

HOMO- AND COPOLYMERIZATION OF SILICON-CONTAINING LACTAMS* K. A. Andrianov, A I. Nogadleli, L. M. Khananashvili, D. Sh. Akeobadze and G. G. Andronikashevili

State University, Tbilisi

M. V. Lomonosov Institute of Fine Chemical Technology, Moscow

(Received 16 July 1972)

The polymerization of methylvinylsilyl-bis-_e_-caprolactone (MVSC) and methyl-vinylsilyl-bis-_e_-caprolactone (MVSP), and their copolymerazaton with methyl methacrylate (MM) or styrene, were studied. Some of the kinetic principles of these processes were also studied and the rate constants for the formation of gel were calculated.

The thermomechanical and thermogravimetric properties of the homo- and copolymers and their unfrared spectra are also described.

The aim of the work reported here was to study the polymerization of methylvinylsilyl-bis-_e_-caprolactone (MVSC) and methylvinylsilyl-bis-_g_-pyrrolidone (MVSP), and their copolymerizations with methyl methacrylate (MM) or styrene [1].

Bulk polymerization of MVSC and MVSP was carried out in the presence of 1% w/w dicumyl peroxide under a nitrogen stream at 120degC. These processes yielded crosslinked polymers as solid, elastic and transparent materials which were not soluble in organic solvents.