# Amphoteric Polyelectrolytes. I. 2-Vinylpyridine-Metacrylic Acid Copolymers1,2
Footnote 1: The poly-dimethylpyridinium salt is a small fraction of the poly-dimethylpyridinium salt, and the poly-dimethylpyridinium salt is a small fraction of the poly-dimethylpyridinium salt.

By Turner Alfrey, Jr., and Herbert Morawetz

# Abstract

Three copolymers of 2-vinylpyridine and methacrylic acid were prepared. These were soluble in some organic solvents and in aqueous acid or base solutions above a critical degree of neutralization. Dilute solution viscosity behavior of one of the copolymers was studied. Both titration and viscosity behavior resembled, in acid solution, that of polyvinylpyridine and, in basic solution, that of polymethacrylic acid. The behavior of the copolymers indicates that they are uncharged, rather than dipolar, ions at their isoelectric points. This is probably due to the weak basicity of the pyridine group.

Many natural substances of biological importance are amphoteric polyelectrolytes, and this has stimulated interest in the investigation of their synthetic analogs.

Polymeric acids such as polyacrylic acid-+ and cationic polymers such as polyvinylamine,7 polyvinylpyridine and quaternary polyvinylpyridinium salts8 have been prepared and studied by a number of investigators. The titration behavior of polymeric acids has been interpreted in terms of (1) the electrical free energy change associated with the removal of protons from the field of the poly-ion and (2) the entropy change accompanying the chain uncoiling which is caused by electrostatic repulsion among the ionic charges.8,9 The dependence of the chain extension on the number of attached ionic charges, and the density of the counter-ion atmosphere, can be followed conveniently by viscosity measurements. The observed effects have been accounted for fairly satisfactorily by a number of theoretical treatments.8,10

The present communication reports an extension of the study of synthetic polyelectrolytes to copolymers carrying both cationic and anionic groups. Such materials behave as polyanions in alkaline solution, and as polycations in acid solution. Particular interest attaches to their behavior near the isoelectric point, and this is determined by the strengths of the ionizing groups.

## Experimental

### Monomers.--2-Vinylpyridine (Reilly Tar and Chem. Co.)

was vacuum distilled under nitrogen (b.p. 61deg at 10 mm.). Because of the tendency of the uninhibited monomer to polymerize slowly even at low temperature, it was always distilled immediately before use.

### Commercial methacrylic acid (Rohm and Haas)

was shaken with sodium chloride, the aqueous layer separated and the acid dehydrated over calcium chloride. It was then vacuum distilled under nitrogen (b.p. 73deg at 20 mm.) and stored at 0deg.

Preparation of Copolymers.--The copolymers were prepared by bulk polymerization under nitrogen at 70deg in presence of 0.05% azo-bis-isobutyronitrile catalyst (du Pont). Conversions of less than 25% were aimed at, in order to obtain copolymers of reasonably homogeneous composition. The copolymers were precipitated and purified by redissibaving twice and reprecipitating in a large excess of non-solvent. They were finally dried to constant weight under vacuum at 70deg. Copolymer compositions calculated from carbon and nitrogen analyses agreed within 2% in all cases and the average of the two values was used. The following resins were prepared:

Copolymer I.--2-Vinylpyridine 28.4 mole % in monomer, 39.3 mole % in polymer. Conversion 12.2% in four hours.

Purified by precipitation from dimethylformamide solution into dioxane.

Copolymer I.--2-Vinylpyridine 50.3 mole % in monomer, 62.1 mole % in polymer. Conversion 24.8% in six hours. Purified by precipitation from methanol-benzene solution into excess methyl ethyl ketone.

Copolymer II.--2-Vinylpyridine 63.2 mole % in monomer, 73.1 mole % in polymer. Conversion 22.2% in four hours. Purified by precipitation from methanol solution into excess methyl ethyl ketone.

The two monomer reactivity ratios11 were computed; the values obtained were \(r\)1 = 1.56 +- 0.1 and \(r\)2 = 0.58 +- 0.05, where the subscript 1 refers to 2-vinylpyridine.

All three copolymers were soluble in nitromethane, dimethylformamide, pyridine and acetic acid. They were all insoluble in acetone, methyl ethyl ketone, ethyl acetate, and either, dioxane, isopropyl alcohol, benzene, toluene, hexane and carbon tetrachloride. Polymer III dissolved in methanol. Polymer II dissolved in methanol-benzene mixtures containing 25 to 65% methanol by volume, and in methanol-water mixtures containing 10 to 25 volume % of water. All resins were insoluble in water and in sodium chloride solutions, but dissolved in dilute aqueous acid or alkali.

Titration.--Samples of 0.25 g. of resin in 80 ml. of water containing two milliequivalents of HCl were titrated with 0.1 \(N\) NaOH, using a Beckman glass electrode pH meter. The titration curves are shown on Fig. 1. It can be seen that each of the resins has an insoluble region. The conditions of solubility are summarized in Table 1.

The pyridine residues are apparently very weakly basic, and no break appears in the titration curve on the acid side. On the alkaline side of the titration curve a break due to the methacrylic acid end-point is observed, but occurs before stoichiometric equivalence is attained (at 91, 85 and 84% of equivalence for copolymers I, II and III, respectively).

The dissociation constants for monomeric methacrylic acid and the 2-vinylpyridinium cation were determined: _pK_a = 4.65 and _pK_a = 5.10, respectively. Pyridinium cations in the copolymers are much more strongly acidic (11) T. Alfrey, Jr., Jr., R. Mayo and P. T. Watt, J. Polymer Sci., 1, 581 (1949).

than the corresponding monomeric vinyl pyridinium ion; on the other hand, metacrylic acid groups in the copolymer are less acidic than monomeric methacrylic acid. When the titration of the copolymer was carried out in presence of 5% sodium chloride, it was found that the pH values were increased in acid and reduced in alkaline solution. The insoluble range was broadened for copolymer II to extend from pH 3.7 to pH 7.3 (3.1 millieg, HCl/g. and 2.7 millieg, NaOH/g., respectively).

Dilute Solution Viscosity.--A modified Ostwald viscosimeter was used. This viscosimeter had a large bulb in which the resin solution could be diluted by addition of measured amounts of solvent.11 All viscosities were measured at 30deg. Copolymer II was chosen as a representative member of the series for detailed investigation of its dilute solution viscosity.

In dimethylformamide, a non-ionizing solvent, the reduced viscosities were low, and decreased very slightly on dilution (0.112, 0.108 and 0.106 at concentrations of 1.0, 0.5 and 0.25 g/100 ml., respectively).

Viscosities were measured in aqueous solutions of various concentrations and degrees of neutralization and, since the resin was insoluble in water below a critical degree of acid or base neutralization, data were also obtained for 90% methanol-10% water solution containing different amounts of acid or base.

Figure 2 is a plot of the specific viscosities at constant polymer concentration, as a function of the acid/resin and base/resin ratios. The aqueous methanol solutions have a viscosity minimum when neither acid nor base is added. The viscosity increase on acid addition is ascribed to the expansion of the chain due to repulsion of the pyridinium cations, while in alkaline solution the polymer expands because of the negatively charged carboxy groups. This charge reversal has been demonstrated previously by electrophoretic measurements.13 The viscosity maxima in water solution correspond to 72% neutralization of the pyridine residues and to 84% neutralization of carboxyl groups. On the basic side the viscosity maximum coincides with the break in the titration curve. It is not unexpected that the viscosity maximum on the acid side should occur at a lower degree of neutralization, since the titration curve shows that the basic strength of the pyridine residues is very low.

Figures 3 and 4 are plots of the reduced viscosities

Figure 4: Viscosities of acid solutions of copolymer II at three different degrees of neutralization.

Figure 3: Viscosities of basic solutions of copolymer II at three different degrees of neutralization.

Figure 2: Solution viscosity of copolymer II as function of degree of neutralization.

of copolymer II in basic and acid solutions, respectively, as a function of dilution. In basic solutions, the reduced viscosity increases on dilution with water in a manner characteristic of strong polyelectrolytes (due to the thinning of the counter-ion atmosphere), and the data fit the relation proposed by Fuoss and Cathers.8 On the other hand, if the resin is partially neutralized with acid, the reduced viscosity has a maximum at 0.25 g/100 ml., and falls off on further dilution. This behavior can be attributed to hydrolysis of the pyridinium cations.

Both the titration behavior and the dilute solution viscosities of the copolymers resemble in acid solution those of polyvinylpyridine and in basic solution those of polymethacrylic acid. This suggests strongly, that the polymer is uncharged in the isoelectric region rather than being a dipolar ion.

## 1 Introduction

Copolymers of methacrylic acid and N,N-diethylaminoethyl methacrylate exist as polycations at low pH, as polystations at high pH, and probably as polysturifections at intermediate pH values. Each copolymer possesses a definite isoelectric point, characterized by a minimum in the solution viscosity and by a reversal in the electrophoretic mobility. The isoelectric point moves to higher pH values, as the amine/acid ratio in the copolymer is increased. If either the amine or the acid constituent is present in large excess, the isoelectric point broadens into a pH range in which the polymer is insoluble.

Synthetic vinyl copolymers containing both acid and basic groups may provide useful analogs to certain aspects of the solution behavior of proteins.3 Previous publications4,5 have discussed copolymers of methacrylic acid with vinylpyridine. The above copolymers were soluble in acid and in alkali, but exhibited water-insolubility in the neutral _r_H range. This was ascribed to the weakly basic character of the pyridine groups, which would preclude zwitterion formation.

Footnote (1): This investigation was supported by the Office of Naval Research, as Project NR-054-022, at the Polytechnic Institute of Brooklin.

This paper describes copolymers containing stronger basic groups, contributed by the monomer N,N-diethylaminoethyl methacrylate (DEAM). Electrophoretic and extensive viscometric studies were made on one member of the series, consisting of approximately 55% methacrylic acid and 45% DEAM. Solubility, titration and less extensive ridsall14 has shown that substances containing both carboxyl and amine groups will form dipolar ions only if the acidity of the carboxyl groups is greater than that of the cationic groups, and this condition is certainly not satisfied in copolymers of vinylpyridine and methacrylic acid. Since it is known that dipolar ions are much more water-soluble than their uncharged isomers,18 the absence of ionic charges at the isoelectric point accounts for the insolubility of the copolymers. Copolymers of strongly basic monomers with methacrylic acid have been shown18 to be soluble over the entire _r_H range, giving strong support for this interpretation.

## 1 Introduction

Copolymers of methacrylic acid and N,N-diethylaminoethyl methacrylate exist as polycations at low pH, as polystations at high pH, and probably as polysturifections at intermediate pH values. Each copolymer possesses a definite isoelectric point, characterized by a minimum in the solution viscosity and by a reversal in the electrophoretic mobility. The isoelectric point moves to higher pH values, as the amine/acid ratio in the copolymer is increased. If either the amine or the acid constituent is present in large excess, the isoelectric point broadens into a pH range in which the polymer is insoluble.

Synthetic vinyl copolymers containing both acid and basic groups may provide useful analogs to certain aspects of the solution behavior of proteins.3 Previous publications4,5 have discussed copolymers of methacrylic acid with vinylpyridine. The above copolymers were soluble in acid and in alkali, but exhibited water-insolubility in the neutral _r_H range. This was ascribed to the weakly basic character of the pyridine groups, which would preclude zwitterion formation.

Footnote (2): Dow Chemical Company, Midland, Michigan.

Footnote (3): R. Standigler, “Die Hochenkreidenz Organischen Verbindungen”, _J. Spränger, Berlin, 1932, p. 39.

Footnote (4): T. Alfrey, Jr., H. M. Morsawetz, E. B. Fitzgerald and R. M. Fouss, **T. Alfrey, Jr., and H. Morsawetz, **84**, **74**, **486** (1952).

This paper describes copolymers containing stronger basic groups, contributed by the monomer N,N-diethylaminoethyl methacrylate (DEAM). Electrophoretic and extensive viscometric studies were made on one member of the series, consisting of approximately 55% methacrylic acid and 45% DEAM. Solubility, titration and less extensive ridsall14 has shown that substances containing both carboxyl and amine groups will form dipolar ions only if the acidity of the carboxyl groups is greater than that of the cationic groups, and this condition is certainly not satisfied in copolymers of vinylpyridine and methacrylic acid. Since it is known that dipolar ions are much more water-soluble than their uncharged isomers,18 the absence of ionic charges at the isoelectric point accounts for the insolubility of the copolymers. Copolymers of strongly basic monomers with methacrylic acid have been shown18 to be soluble over the entire _r_H range, giving strong support for this interpretation.

Footnote (5): R. J. Cohn and J. T. Bdsall, “Proteins, Amino Acids and Peptides,” Reinhold Publishing Corp., New York, N. Y., 1943, chapter 8.

## 2 Introduction

Copolymers of methacrylic acid and N,N-diethylaminoethyl methacrylate exist as polycations at low pH, as polystations at high pH, and probably as polysturifections at intermediate pH values. Each copolymer possesses a definite isoelectric point, characterized by a minimum in the solution viscosity and by a reversal in the electrophoretic mobility. The isoelectric point moves to higher pH values, as the amine/acid ratio in the copolymer is increased. If either the amine or the acid constituent is present in large excess, the isoelectric point broadens into a pH range in which the polymer is insoluble.

Synthetic vinyl copolymers containing both acid and basic groups may provide useful analogs to certain aspects of the solution behavior of proteins.3 Previous publications4,5 have discussed copolymers of methacrylic acid with vinylpyridine. The above copolymers were soluble in acid and in alkali, but exhibited water-insolubility in the neutral _r_H range. This was ascribed to the weakly basic character of the pyridine groups, which would preclude zwitterion formation.

Footnote (6): R. J. Cohn and J. T. Bdsall, “Proteins, Amino Acids and Peptides,” Reinhold Publishing Corp., New York, N. Y., 1943, chapter 8.