wandb_version: 1

model:
  desc: null
  value: gpt-4-turbo-preview
temperature:
  desc: null
  value: 0.0
paper number:
  desc: null
  value: 10
token length:
  desc: null
  value: ''
input:
  desc: null
  value: PDF
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.2
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708614613.480799
    t:
      1:
      - 5
      - 53
      - 54
      - 55
      - 95
      - 105
      2:
      - 5
      - 53
      - 54
      - 55
      - 95
      - 105
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.16.2
      8:
      - 4
      - 5
      13: darwin-arm64
