wandb_version: 1

model:
  desc: null
  value: gpt-3.5-turbo-1106
paper number:
  desc: null
  value: 10
token length:
  desc: null
  value: 1024
input:
  desc: null
  value: markdown form NOUGAT
number of model calls max:
  desc: null
  value: 3
number of model calls min:
  desc: null
  value: 1
temperature:
  desc: null
  value: 0.0
max resolution:
  desc: null
  value: ''
deviation of correct rxn:
  desc: null
  value: 0.01
input tokens used:
  desc: null
  value: 51947
output tokens used:
  desc: null
  value: 5930
total model calls:
  desc: null
  value: 26
time used:
  desc: null
  value: 175.58204078674316
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.2
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712913897.793027
    t:
      1:
      - 5
      - 53
      - 54
      - 55
      - 95
      - 97
      - 105
      2:
      - 5
      - 53
      - 54
      - 55
      - 95
      - 97
      - 105
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.16.2
      8:
      - 4
      - 5
      13: darwin-arm64
